#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Issue #92, slice 1.6: measure the undocumented facts the walking skeleton
# builds on (ADRs 0006, 0016, 0017, 0027, 0031, 0032). Everything runs on
# throwaway Workers, one KV namespace, one R2 bucket and five public repos.
#
# The spikes that need a day or more (billed KV usage, GitHub's retention
# sweep, Dependabot) are set up early and read back in the last stages, so
# expect to run this wizard twice: a recorded spike is skipped on a re-run.
#
#   scripts/spike-92-early-spikes.sh                  run or resume
#   SPIKE_FIXTURES_ONLY=1 scripts/spike-92-early-spikes.sh
#                                                     write the Workers and the
#                                                     OpenTofu root to the work
#                                                     directory and stop

TOTAL_STAGES=19

ISSUE_REPO="andrewferk/url-shortener"
ISSUE_NUMBER=92
PRD_NUMBER=40
PREFIX="${SPIKE_PREFIX:-spike92}"
WRANGLER_VERSION="${WRANGLER_VERSION:-4.147.0}"
KV_READS="${KV_READS:-1000}"
LOCK_ROUNDS="${LOCK_ROUNDS:-5}"
HOLD_SECONDS=20

KV_WORKER="$PREFIX-kv"
LD_WORKER="$PREFIX-links-data"
WORKFLOW_NAME="$PREFIX-touch-shards"
BUCKET="$PREFIX-state"
RET_NAME="$PREFIX-retention"
DBOT_CONSUMER_NAME="$PREFIX-dbot-consumer"
DBOT_CASES="notag tagbehind tagged"

# State (the account ID, throwaway tokens, outcomes) lives outside the repo:
# no deployment value may land in it. The last stage deletes the state file.
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/url-shortener-spike-92"
WORK="$STATE_DIR/work"
LOGS="$STATE_DIR/logs"
mkdir -p "$STATE_DIR" "$WORK" "$LOGS"
chmod 700 "$STATE_DIR"
ENV_FILE="$STATE_DIR/state.env"
RESULT_FILE="$STATE_DIR/result.md"
touch "$ENV_FILE"; chmod 600 "$ENV_FILE"

die() { printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2; exit 1; }
ok()  { printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }
bad() { printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"; }

# get KEY: a recorded value, or nothing.
get() { _existing "$1" || true; }
# record KEY VALUE: keep an outcome, on one line, without the library's chatter.
record() {
  local value tmp
  value=$(printf '%s' "$2" | tr '\n\r' '  ')
  tmp=$(mktemp)
  grep -vE "^${1}=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$1" "$value" >>"$tmp"
  mv "$tmp" "$ENV_FILE"
}
# load KEY...: read recorded values back into shell variables.
load() { local k; for k in "$@"; do printf -v "$k" '%s' "$(get "$k")"; done; }

# begin RESULT_KEY: decide whether this stage's spike runs. A recorded spike
# is skipped unless the human asks to redo it.
begin() {
  local current
  current=$(get "$1")
  if [[ -n "$current" ]]; then
    ok "already recorded: $current"
    if confirm "Run it again?"; then return 0; fi
    return 1
  fi
  if confirm "Skip this one for now?"; then return 1; fi
  return 0
}
# need KEY "what to do": a later stage depends on an earlier one.
need() {
  if [[ -z "$(get "$1")" ]]; then
    warn "$2"
    return 1
  fi
}

# quiet LOG CMD...: run CMD with its output in LOG; return its exit code.
quiet() {
  local log="$1"; shift
  "$@" >"$log" 2>&1
}
# loud LOG CMD...: the same, but the human watches the output too.
loud() {
  local log="$1" rc=0; shift
  "$@" 2>&1 | tee "$log" || rc=${PIPESTATUS[0]}
  return "$rc"
}

# scrub: take deployment values out of anything that is recorded.
scrub() {
  local account sub
  account=$(get CF_ACCOUNT_ID); sub=$(get WORKERS_SUBDOMAIN)
  sed -e "s/${account:-__none__}/<account-id>/g" \
      -e "s/${sub:-__none__}\.workers\.dev/<subdomain>.workers.dev/g"
}
# plain: strip terminal colours.
ESC=$(printf '\033')
plain() { sed -e "s/${ESC}\[[0-9;]*[A-Za-z]//g"; }
# excerpt LOG: the first error lines of a log, on one line, scrubbed.
excerpt() {
  local out
  out=$(grep -iE 'error|denied|forbidden|fail|not (allowed|authorized|supported)|unauthorized' "$1" 2>/dev/null \
    | head -n 4 | plain | tr '\n' ' ' | tr -s ' ' | cut -c1-400 | scrub) || true
  [[ -n "$out" ]] || out=$(tail -n 3 "$1" 2>/dev/null | plain | tr '\n' ' ' | tr -s ' ' | cut -c1-400 | scrub) || true
  printf '%s' "$out"
}

days_ago() {
  if date -u -v-1d +%s >/dev/null 2>&1; then date -u -v-"$1"d +%Y-%m-%dT%H:%M:%SZ
  else date -u -d "$1 days ago" +%Y-%m-%dT%H:%M:%SZ; fi
}
day_offset() { # day_offset -1 | +1 → YYYY-MM-DD
  if date -u -v-1d +%s >/dev/null 2>&1; then date -u -v"$1"d +%Y-%m-%d
  else date -u -d "$1 day" +%Y-%m-%d; fi
}

# ── Cloudflare ────────────────────────────────────────────────────────────

# wr TOKEN DIR ARGS...: Wrangler, pinned, as one token, inside one directory.
wr() {
  local token="$1" dir="$2"; shift 2
  ( cd "$dir" && CLOUDFLARE_API_TOKEN="$token" CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID" \
      npx --yes "wrangler@$WRANGLER_VERSION" "$@" )
}

# cf TOKEN METHOD PATH [JSON]: one API call. The body lands in $CF_BODY (a
# file) and the HTTP status in $CF_STATUS.
CF_BODY="$WORK/cf-body.json"; CF_STATUS=""
cf() {
  local token="$1" method="$2" path="$3" data="${4:-}"
  local args=(-sS -o "$CF_BODY" -w '%{http_code}' -X "$method"
              -H "Authorization: Bearer $token" -H 'Content-Type: application/json')
  if [[ -n "$data" ]]; then args+=(--data "$data"); fi
  CF_STATUS=$(curl "${args[@]}" "https://api.cloudflare.com/client/v4$path") || CF_STATUS="curl-failed"
}
cf_error() { jq -r '[.errors[]? | "\(.code) \(.message)"] | join("; ")' "$CF_BODY" 2>/dev/null | cut -c1-300 | scrub; }

# probe URL: one GET of a throwaway Worker. The body lands in $PROBE_BODY and
# a copy in the probe log, the HTTP status in $PROBE_STATUS ("" if curl
# itself failed, e.g. DNS). Returns curl's status.
PROBE_BODY="$WORK/probe-body"; PROBE_STATUS=""
probe() {
  PROBE_STATUS=$(curl -sS -o "$PROBE_BODY" -w '%{http_code}' --max-time 60 "$1" 2>"$LOGS/ld-probe.log") || PROBE_STATUS=""
  { printf '%s HTTP %s\n' "$(date '+%H:%M:%S')" "${PROBE_STATUS:-none}"; cat "$PROBE_BODY" 2>/dev/null; printf '\n'; } >>"$LOGS/ld-probe.log"
  [[ -n "$PROBE_STATUS" ]]
}

# token_ok TOKEN: is this an active token on the account? Account-owned and
# user-owned tokens verify at different paths.
token_ok() {
  cf "$1" GET "/accounts/$CF_ACCOUNT_ID/tokens/verify"
  if [[ "$CF_STATUS" == 200 ]] && jq -e '.result.status == "active"' "$CF_BODY" >/dev/null 2>&1; then return 0; fi
  cf "$1" GET "/user/tokens/verify"
  [[ "$CF_STATUS" == 200 ]] && jq -e '.result.status == "active"' "$CF_BODY" >/dev/null 2>&1
}

# ── Fixtures: the throwaway Workers ───────────────────────────────────────

# The KV Worker: one KV read per request, with the cacheTtl ADR 0006 uses.
write_kv_worker() {
  local dir="$WORK/kv-worker"
  mkdir -p "$dir"
  cat >"$dir/index.js" <<'JS'
export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.searchParams.get("k") !== env.SPIKE_KEY) return new Response("no\n", { status: 403 });
    const value = await env.KV.get("spike", { cacheTtl: 30 });
    const colo = request.cf && request.cf.colo ? request.cf.colo : "unknown";
    return new Response(`colo=${colo} value=${value === null ? "MISSING" : "ok"}\n`);
  },
};
JS
  cat >"$dir/wrangler.jsonc" <<JSON
{
  "name": "$KV_WORKER",
  "main": "index.js",
  "compatibility_date": "2026-10-01",
  "workers_dev": true,
  "kv_namespaces": [{ "binding": "KV", "id": "${KV_NAMESPACE_ID:-00000000000000000000000000000000}" }],
  "vars": { "SPIKE_KEY": "${SPIKE_KEY:-fixture}" }
}
JSON
}

# The links-data stand-in: a SQLite Durable Object class declared with
# `exports` (ADR 0027), a Workflow that touches objects (ADR 0031), and a
# keyed route so the wizard can ask an object where it is (ADR 0017).
write_ld_worker() {
  local dir="$WORK/links-data"
  mkdir -p "$dir"
  cat >"$dir/index.js" <<'JS'
import { DurableObject, WorkflowEntrypoint } from "cloudflare:workers";

const HINTS = ["wnam", "enam", "weur", "apac", "oc"];

// Every way this spike knows for an object to learn where it runs.
export class Shard extends DurableObject {
  async fetch(request) {
    const report = { trace_colo: null, trace_loc: null, trace_error: null };
    try {
      const response = await fetch("https://www.cloudflare.com/cdn-cgi/trace");
      const text = await response.text();
      const colo = text.match(/^colo=(.+)$/m);
      const loc = text.match(/^loc=(.+)$/m);
      report.trace_colo = colo ? colo[1] : null;
      report.trace_loc = loc ? loc[1] : null;
    } catch (error) {
      report.trace_error = String(error);
    }
    // What the caller's request carries into the object, for comparison.
    report.cf_colo_on_request = request.cf && request.cf.colo ? request.cf.colo : null;
    // Anything on the object's own context that might name a place.
    const names = (value) => {
      const found = new Set();
      for (let o = value; o && o !== Object.prototype; o = Object.getPrototypeOf(o)) {
        for (const name of Object.getOwnPropertyNames(o)) found.add(name);
      }
      return [...found].sort();
    };
    report.ctx_properties = names(this.ctx);
    report.id_properties = names(this.ctx.id);
    return Response.json(report);
  }
}

async function touch(env, hint, name) {
  const id = env.SHARD.idFromName(name);
  const stub = env.SHARD.get(id, { locationHint: hint });
  const response = await stub.fetch("https://shard.invalid/where");
  return { hint, name, ...(await response.json()) };
}

// The stand-in for ADR 0031's touch-shards Workflow.
export class TouchShards extends WorkflowEntrypoint {
  async run(event, step) {
    return await step.do("touch", async () => {
      const run = event.instanceId || String(Date.now());
      const report = [];
      for (const hint of HINTS) report.push(await touch(this.env, hint, `wf-${hint}-${run}`));
      return report;
    });
  }
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.searchParams.get("k") !== env.SPIKE_KEY) return new Response("no\n", { status: 403 });
    const hint = url.searchParams.get("hint") || "weur";
    const name = url.searchParams.get("name") || `direct-${hint}-${Date.now()}`;
    const id = env.SHARD.idFromName(name);
    const stub = env.SHARD.get(id, { locationHint: hint });
    const response = await stub.fetch(request);
    return Response.json({
      hint,
      name,
      worker_colo: request.cf && request.cf.colo ? request.cf.colo : null,
      ...(await response.json()),
    });
  },
};
JS
  cat >"$dir/wrangler.jsonc" <<JSON
{
  "name": "$LD_WORKER",
  "main": "index.js",
  "compatibility_date": "2026-10-01",
  "workers_dev": true,
  "durable_objects": { "bindings": [{ "name": "SHARD", "class_name": "Shard" }] },
  "exports": { "Shard": { "type": "durable-object", "storage": "sqlite" } },
  "workflows": [{ "name": "$WORKFLOW_NAME", "binding": "TOUCH", "class_name": "TouchShards" }],
  "vars": { "SPIKE_KEY": "${SPIKE_KEY:-fixture}" }
}
JSON
}

# ── Fixtures: the OpenTofu root ───────────────────────────────────────────

# write_root DIR STATE_KEY PRIMARY [FALLBACK]: a root with no cloud provider,
# its state on R2 and encrypted as ADR 0027 has it. PRIMARY and FALLBACK are
# the key provider names; the passphrases come from TF_VAR_passphrase_primary
# and TF_VAR_passphrase_fallback.
write_root() {
  local dir="$1" key="$2" primary="$3" fallback="${4:-}"
  mkdir -p "$dir"
  {
    cat <<HCL
terraform {
  required_version = "~> 1.13.0"

  backend "s3" {}

  encryption {
    key_provider "pbkdf2" "$primary" {
      passphrase = var.passphrase_primary
    }
    method "aes_gcm" "$primary" {
      keys = key_provider.pbkdf2.$primary
    }
HCL
    if [[ -n "$fallback" ]]; then
      cat <<HCL
    key_provider "pbkdf2" "$fallback" {
      passphrase = var.passphrase_fallback
    }
    method "aes_gcm" "$fallback" {
      keys = key_provider.pbkdf2.$fallback
    }
HCL
    fi
    for target in state plan; do
      printf '    %s {\n      method   = method.aes_gcm.%s\n      enforced = true\n' "$target" "$primary"
      if [[ -n "$fallback" ]]; then
        printf '      fallback {\n        method = method.aes_gcm.%s\n      }\n' "$fallback"
      fi
      printf '    }\n'
    done
    cat <<'HCL'
  }
}

variable "passphrase_primary" {
  type      = string
  sensitive = true
}
HCL
    if [[ -n "$fallback" ]]; then
      cat <<'HCL'

variable "passphrase_fallback" {
  type      = string
  sensitive = true
}
HCL
    fi
    cat <<'HCL'

# ADR 0032's rotation marker: `reencrypt` raises it so an apply has something
# to write.
variable "rotation_marker" {
  type    = number
  default = 1
}

resource "terraform_data" "rotation_marker" {
  input = var.rotation_marker
}

# The lock spike: an apply that holds the state lock for a while.
variable "round" {
  type    = number
  default = 0
}

variable "hold_seconds" {
  type    = number
  default = 0
}

resource "terraform_data" "hold" {
  triggers_replace = [var.round]

  provisioner "local-exec" {
    command = "sleep ${var.hold_seconds}"
  }
}
HCL
  } >"$dir/main.tf"
  cat >"$dir/backend.hcl" <<HCL
bucket = "$BUCKET"
key    = "$key"
region = "auto"
endpoints = {
  s3 = "https://${CF_ACCOUNT_ID:-ACCOUNT_ID}.r2.cloudflarestorage.com"
}
skip_credentials_validation = true
skip_metadata_api_check     = true
skip_region_validation      = true
skip_requesting_account_id  = true
skip_s3_checksum            = true
use_path_style              = true
use_lockfile                = true
HCL
}

# tf DIR rw|ro ARGS...: OpenTofu in DIR with the read-write or the read-only
# R2 key. Callers export the passphrases.
tf() {
  local dir="$1" kind="$2" id secret; shift 2
  if [[ "$kind" == ro ]]; then id="$R2_RO_KEY_ID"; secret="$R2_RO_SECRET"
  else id="$R2_RW_KEY_ID"; secret="$R2_RW_SECRET"; fi
  ( cd "$dir" && AWS_ACCESS_KEY_ID="$id" AWS_SECRET_ACCESS_KEY="$secret" AWS_REGION=auto \
      TF_IN_AUTOMATION=1 TF_INPUT=0 tofu "$@" )
}
tf_init() { tf "$1" "$2" init -input=false -no-color -reconfigure -backend-config=backend.hcl; }
lock_error() { grep -q 'Error acquiring the state lock' "$1" 2>/dev/null; }

if [[ -n "${SPIKE_FIXTURES_ONLY:-}" ]]; then
  CF_ACCOUNT_ID=""; write_kv_worker; write_ld_worker
  write_root "$WORK/fixture-root-single" "fixture/terraform.tfstate" current
  write_root "$WORK/fixture-root-rotating" "fixture/terraform.tfstate" current previous
  printf 'Fixtures written under %s\n' "$WORK"
  exit 0
fi

# ── GitHub ────────────────────────────────────────────────────────────────

# commit_file OWNER/REPO PATH CONTENT [ISO_DATE]: create or replace one file
# on the default branch through the API and print the commit's SHA. A date
# backdates the commit, which Dependabot's cooldown looks at.
commit_file() {
  local repo="$1" path="$2" content="$3" when="${4:-}" sha="" out args
  if out=$(gh api "repos/$repo/contents/$path" --jq .sha 2>/dev/null); then sha="$out"; fi
  args=(-X PUT "repos/$repo/contents/$path"
        -f "message=Spike #$ISSUE_NUMBER: $path"
        -f "content=$(printf '%s\n' "$content" | base64 | tr -d '\n')")
  if [[ -n "$sha" ]]; then args+=(-f "sha=$sha"); fi
  if [[ -n "$when" ]]; then
    args+=(-f "committer[name]=spike" -f "committer[email]=spike@example.invalid" -f "committer[date]=$when"
           -f "author[name]=spike" -f "author[email]=spike@example.invalid" -f "author[date]=$when")
  fi
  gh api "${args[@]}" --jq .commit.sha || die "couldn't write $path to $repo."
}

ensure_repo() {
  local repo="$1" desc="$2"
  if gh repo view "$repo" >/dev/null 2>&1; then
    ok "$repo already exists"
  else
    gh repo create "$repo" --public --add-readme --description "$desc" >/dev/null \
      || die "couldn't create $repo."
    ok "created $repo (public)"
    sleep 3
  fi
}

ensure_workflow_scope() {
  local headers
  headers=$(gh api -i user 2>/dev/null | grep -i '^x-oauth-scopes:' || true)
  if grep -qw workflow <<<"$headers"; then return 0; fi
  say "gh's token can't write workflow files (it lacks the 'workflow' scope)."
  pause "Press Enter to run: gh auth refresh -h github.com -s workflow"
  gh auth refresh -h github.com -s workflow || die "gh auth refresh failed; re-run the wizard."
}

# ── Preflight ─────────────────────────────────────────────────────────────

for tool in gh jq curl openssl node npx; do
  command -v "$tool" >/dev/null 2>&1 || die "$tool is not installed."
done
command -v tofu >/dev/null 2>&1 \
  || die "OpenTofu is not installed. ADR 0027 pins 1.13.x: 'mise use -g opentofu@1.13.1', or 'brew install opentofu'."
TOFU_VERSION=$(tofu version -json 2>/dev/null | jq -r .terraform_version 2>/dev/null || true)
case "$TOFU_VERSION" in
  1.13.*) ;;
  *) die "tofu is ${TOFU_VERSION:-an unknown version}; the spikes are about 1.13.x (ADR 0027). Try: mise use -g opentofu@1.13.1" ;;
esac
GH_LOGIN=$(gh api user --jq .login 2>/dev/null) || die "gh is not logged in; run: gh auth login"
RET_REPO="$GH_LOGIN/$RET_NAME"
DBOT_CONSUMER="$GH_LOGIN/$DBOT_CONSUMER_NAME"

load CF_ACCOUNT_ID CF_SETUP_TOKEN SPIKE_KEY KV_NAMESPACE_ID \
     R2_RW_KEY_ID R2_RW_SECRET R2_RO_KEY_ID R2_RO_SECRET \
     CF_ADMIN_TOKEN CF_PLAN_TOKEN LD_URL KV_URL ROLE_TOKEN_NOTE
if [[ -z "$SPIKE_KEY" ]]; then
  SPIKE_KEY=$(openssl rand -hex 16); record SPIKE_KEY "$SPIKE_KEY"
fi

# conclude KEY yes|no FALLBACK_TEXT SUMMARY: the one-line result of a spike,
# and whether it takes the fallback its ADR decided in advance.
conclude() {
  record "R_$1_FALLBACK" "$2"
  record "R_$1_CHANGES" "$3"
  record "R_$1" "$4"
  printf '\n'
  if [[ "$2" == yes ]]; then warn "Result: $4"; warn "Fallback taken: $3"
  else ok "Result: $4"; fi
}

track_key() { record STATE_KEYS "$(get STATE_KEYS) $1"; }
RUN=$(date -u +%m%d%H%M%S)

banner "Spike #$ISSUE_NUMBER: measure the undocumented facts the walking skeleton builds on"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Pick the Cloudflare account"
say "Every Cloudflare spike runs on throwaway resources named ${BOLD}$PREFIX-…${RESET} in one account."
say "Use the account the deployment will live in, or any account you can bill."
note "Workers Free is enough to run them. Billed usage (the KV spike) only shows on a pay-as-you-go account."
open_url "https://dash.cloudflare.com/"
step "Choose the account. Its ID is the 32-character hex string in the address bar:"
step "  dash.cloudflare.com/${BOLD}<account id>${RESET}/home"
ask CF_ACCOUNT_ID "Paste the account ID:"
[[ "$CF_ACCOUNT_ID" =~ ^[0-9a-f]{32}$ ]] || die "an account ID is 32 lowercase hex characters."
write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
note "It stays in $ENV_FILE, outside the repo, and is scrubbed from every recorded result."
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the setup token"
say "One throwaway, account-owned API token creates and removes the spike's resources."
open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/home"
step "Go to ${BOLD}Manage Account → Account API Tokens → Create Token${RESET}, and choose a custom token."
step "Name it ${BOLD}$PREFIX-setup${RESET} and give it these Account permissions:"
step "    Workers Scripts: Edit"
step "    Workers KV Storage: Edit"
step "    Workers R2 Storage: Edit"
step "    Account Analytics: Read"
step "Limit it to this one account and set it to expire in a week."
step "${BOLD}Continue to summary → Create Token${RESET}, then copy the token (it is shown once)."
ask_secret CF_SETUP_TOKEN "Paste the setup token:"
[[ -n "$CF_SETUP_TOKEN" ]] || die "the setup token is required."
token_ok "$CF_SETUP_TOKEN" || die "Cloudflare doesn't accept that token for this account (HTTP $CF_STATUS: $(cf_error))."
ok "the token is active"
write_env CF_SETUP_TOKEN "$CF_SETUP_TOKEN"
note "If a later deploy fails on authentication, add 'Account Settings: Read' to this token and re-run."
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "KV cached reads: read one key $KV_READS times (ADR 0006)"
spike_kv_run() {
  begin KV_READS_SENT || return 0
  say "This creates the KV namespace ${BOLD}$KV_WORKER${RESET} and a Worker of the same name on workers.dev."
  say "The Worker does one KV read per request, with cacheTtl 30. The wizard then sends"
  say "$KV_READS requests from this machine inside one cacheTtl. Analytics and the bill are read in stage 15."
  confirm "Create them and run the reads?" || return 0
  local dir="$WORK/kv-worker" list warm="$LOGS/kv-warm.out" out="$LOGS/kv-burst.out" url started ended total colos i
  list=$(wr "$CF_SETUP_TOKEN" "$WORK" kv namespace list 2>/dev/null || true)
  KV_NAMESPACE_ID=$(jq -r --arg t "$KV_WORKER" '[.[] | select(.title == $t or (.title | endswith($t)))][0].id // empty' <<<"$list" 2>/dev/null || true)
  if [[ -z "$KV_NAMESPACE_ID" ]]; then
    loud "$LOGS/kv-create.log" wr "$CF_SETUP_TOKEN" "$WORK" kv namespace create "$KV_WORKER" \
      || die "couldn't create the KV namespace."
    list=$(wr "$CF_SETUP_TOKEN" "$WORK" kv namespace list 2>/dev/null || true)
    KV_NAMESPACE_ID=$(jq -r --arg t "$KV_WORKER" '[.[] | select(.title == $t or (.title | endswith($t)))][0].id // empty' <<<"$list" 2>/dev/null || true)
  fi
  if [[ -z "$KV_NAMESPACE_ID" ]]; then
    ask KV_NAMESPACE_ID "Couldn't read the namespace ID back. Paste it from the output above:"
  fi
  [[ "$KV_NAMESPACE_ID" =~ ^[0-9a-f]{32}$ ]] || die "a KV namespace ID is 32 hex characters."
  write_env KV_NAMESPACE_ID "$KV_NAMESPACE_ID"
  loud "$LOGS/kv-put.log" wr "$CF_SETUP_TOKEN" "$WORK" kv key put spike value --namespace-id "$KV_NAMESPACE_ID" --remote \
    || die "couldn't write the key."
  write_kv_worker
  say "Deploying. If Wrangler asks to register a workers.dev subdomain, say yes."
  loud "$LOGS/kv-deploy.log" wr "$CF_SETUP_TOKEN" "$dir" deploy || die "the deploy failed."
  url=$(grep -oE 'https://[A-Za-z0-9.-]+\.workers\.dev' "$LOGS/kv-deploy.log" | tail -n 1 || true)
  if [[ -z "$url" ]]; then ask KV_URL "Paste the workers.dev URL Wrangler printed:"; url="$KV_URL"; fi
  [[ "$url" == https://*.workers.dev* ]] || die "that isn't a workers.dev URL."
  url="${url%/}"
  write_env KV_URL "$url"
  record WORKERS_SUBDOMAIN "$(sed -E 's#https://[^.]+\.([^.]+)\.workers\.dev.*#\1#' <<<"$url")"
  : >"$warm"
  say "Waiting for the Worker and the key to be readable…"
  for i in $(seq 1 24); do
    curl -s "$url/?k=$SPIKE_KEY&warm=$i" >>"$warm" || true
    if tail -n 1 "$warm" | grep -q 'value=ok'; then break; fi
    sleep 5
  done
  tail -n 1 "$warm" | grep -q 'value=ok' || die "the Worker never returned the key; see $warm."
  ok "the key reads back; sending $KV_READS requests"
  started=$(date +%s)
  curl -s --parallel --parallel-max 20 "$url/?k=$SPIKE_KEY&i=[1-$KV_READS]" >"$out" || true
  ended=$(date +%s)
  total=$(cat "$warm" "$out" | grep -c '^colo=' || true)
  colos=$(sed -n 's/^colo=\([^ ]*\).*/\1/p' "$out" | sort | uniq -c | awk '{printf "%s×%s ", $2, $1}')
  say "Reads made: ${BOLD}$total${RESET} (warm-up included), the burst in $((ended - started)) s, from: $colos"
  if (( ended - started > 30 )); then warn "The burst took longer than one cacheTtl (30 s). Consider running it again with KV_READS=500."; fi
  if [[ "$(wc -w <<<"$colos")" -gt 1 ]]; then warn "More than one colo answered; the ADR asks for one location. Record it anyway."; fi
  record KV_DATE "$(date -u +%Y-%m-%d)"
  record KV_AT "$(date -u +%H:%M)"
  record KV_SECONDS "$((ended - started))"
  record KV_COLOS "$colos"
  record KV_READS_SENT "$total"
  ok "recorded. Stage 15 reads KV analytics and the billed figure; that one waits a day."
}
spike_kv_run
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the state bucket and its two R2 keys"
r2_setup() {
  if [[ -n "$R2_RW_SECRET" && -n "$R2_RO_SECRET" ]]; then
    ok "the bucket's keys are already saved"
    confirm "Enter them again?" || return 0
  fi
  say "Three OpenTofu spikes share one throwaway R2 bucket, ${BOLD}$BUCKET${RESET}."
  cf "$CF_SETUP_TOKEN" GET "/accounts/$CF_ACCOUNT_ID/r2/buckets/$BUCKET"
  if [[ "$CF_STATUS" == 200 ]]; then ok "the bucket already exists"
  elif loud "$LOGS/r2-create.log" wr "$CF_SETUP_TOKEN" "$WORK" r2 bucket create "$BUCKET"; then ok "bucket created"
  else
    warn "the create failed (log: $LOGS/r2-create.log)."
    note "R2 needs its billing enabled first: R2 Object Storage → Overview → Purchase R2 (there is a free tier)."
    note "If that was it, enable it and re-run the wizard; this stage retries the create."
    die "no bucket named $BUCKET, so its keys can't be made yet."
  fi
  say "Now two S3 keys for it. Only you can make these."
  open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/r2/overview"
  step "On the R2 page, under ${BOLD}Account Details${RESET}, click ${BOLD}Manage${RESET} next to API Tokens."
  step "Create an ${BOLD}Account API token${RESET} named $PREFIX-rw: ${BOLD}Object Read & Write${RESET}, applied to the bucket $BUCKET only."
  step "Copy its Access Key ID and Secret Access Key (the secret is shown once)."
  ask R2_RW_KEY_ID "Read-write Access Key ID:"
  ask_secret R2_RW_SECRET "Read-write Secret Access Key:"
  step "Create a second one named $PREFIX-ro: ${BOLD}Object Read only${RESET}, the same bucket only."
  ask R2_RO_KEY_ID "Read-only Access Key ID:"
  ask_secret R2_RO_SECRET "Read-only Secret Access Key:"
  [[ -n "$R2_RW_KEY_ID" && -n "$R2_RW_SECRET" && -n "$R2_RO_KEY_ID" && -n "$R2_RO_SECRET" ]] || die "all four values are required."
  [[ "$R2_RW_KEY_ID" != "$R2_RO_KEY_ID" ]] || die "the two keys are the same one."
  write_env R2_RW_KEY_ID "$R2_RW_KEY_ID"; write_env R2_RW_SECRET "$R2_RW_SECRET"
  write_env R2_RO_KEY_ID "$R2_RO_KEY_ID"; write_env R2_RO_SECRET "$R2_RO_SECRET"
}
r2_setup
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Read-only planning: tofu plan -lock=false with a read-only key (ADR 0027)"
spike_ro() {
  need R2_RO_SECRET "Stage 4 hasn't saved the R2 keys yet; re-run the wizard to do it." || return 0
  begin R_RO || return 0
  local key="ro-plan-$RUN/terraform.tfstate" rw="$WORK/tofu/ro-rw" ro="$WORK/tofu/ro-ro"
  local rc_init=0 rc_plan=0 rc_ctl=0 rc_after=0 init_note="" summary
  rm -rf "$rw" "$ro"
  export TF_VAR_passphrase_primary; TF_VAR_passphrase_primary=$(openssl rand -hex 32)
  track_key "$key"
  write_root "$rw" "$key" current
  write_root "$ro" "$key" current
  say "Writing a state with the read-write key…"
  quiet "$LOGS/ro-setup-init.log" tf_init "$rw" rw || die "tofu init failed against R2: $(excerpt "$LOGS/ro-setup-init.log")"
  quiet "$LOGS/ro-setup-apply.log" tf "$rw" rw apply -auto-approve -no-color \
    || die "tofu apply failed against R2: $(excerpt "$LOGS/ro-setup-apply.log")"
  ok "state written and encrypted"
  say "Now the read-only key, in a fresh directory:"
  quiet "$LOGS/ro-init.log" tf_init "$ro" ro || rc_init=$?
  if [[ "$rc_init" == 0 ]]; then ok "tofu init"
  else
    bad "tofu init failed: $(excerpt "$LOGS/ro-init.log")"
    init_note=" (init itself needed the read-write key)"
    quiet "$LOGS/ro-init-rw.log" tf_init "$ro" rw || die "init fails with the read-write key too; see $LOGS/ro-init-rw.log"
  fi
  quiet "$LOGS/ro-plan.log" tf "$ro" ro plan -no-color -lock=false -out=plan.bin || rc_plan=$?
  if [[ "$rc_plan" == 0 ]]; then ok "tofu plan -lock=false -out=plan.bin"
  else bad "tofu plan -lock=false failed: $(excerpt "$LOGS/ro-plan.log")"; fi
  say "Control: the same key with locking on must be refused, or the key isn't read-only."
  quiet "$LOGS/ro-control.log" tf "$ro" ro plan -no-color -lock-timeout=0s || rc_ctl=$?
  if [[ "$rc_ctl" != 0 ]]; then ok "refused, as it should be: $(excerpt "$LOGS/ro-control.log")"
  else bad "a locking plan succeeded: this key can write"; fi
  quiet "$LOGS/ro-after.log" tf "$rw" rw plan -no-color -lock-timeout=0s || rc_after=$?
  if [[ "$rc_after" == 0 ]]; then ok "no lock was left behind by the refused plan"
  else bad "the read-write key can't lock afterwards: $(excerpt "$LOGS/ro-after.log")"; fi
  unset TF_VAR_passphrase_primary
  summary="OpenTofu $TOFU_VERSION. Read-only key: init exit $rc_init$init_note, plan -lock=false -out exit $rc_plan; control (locking plan, same key) exit $rc_ctl; read-write locking plan afterwards exit $rc_after."
  if [[ "$rc_ctl" == 0 ]]; then
    record R_RO_FALLBACK pending
    warn "The key isn't read-only, so nothing is proven. Recreate $PREFIX-ro as Object Read only (stage 4) and run this again."
    return 0
  fi
  if [[ "$rc_plan" == 0 && "$rc_init" == 0 ]]; then
    conclude RO no "" "Works. $summary"
  elif [[ "$rc_plan" == 0 ]]; then
    conclude RO yes "production-plan takes a read-write state key, unless init can be made to work read-only (slices 1.4, 1.5)." "Plan works, init doesn't. $summary $(excerpt "$LOGS/ro-init.log")"
  else
    conclude RO yes "production-plan takes a read-write state key (slices 1.4, 1.5)." "Fails. $summary $(excerpt "$LOGS/ro-plan.log")"
  fi
}
spike_ro
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Lock contention: two applies at once against one state (ADR 0027, ADR 0032)"
spike_lock() {
  need R2_RW_SECRET "Stage 4 hasn't saved the R2 keys yet; re-run the wizard to do it." || return 0
  begin R_LOCK || return 0
  local key="lock-$RUN/terraform.tfstate" a="$WORK/tofu/lock-a" b="$WORK/tofu/lock-b"
  local r pa pb ca cb one=0 both=0 neither=0 odd=0 leftover=0 waiter="not run" id rc summary
  rm -rf "$a" "$b"
  export TF_VAR_passphrase_primary; TF_VAR_passphrase_primary=$(openssl rand -hex 32)
  track_key "$key"
  write_root "$a" "$key" current; write_root "$b" "$key" current
  quiet "$LOGS/lock-init-a.log" tf_init "$a" rw || die "tofu init failed: $(excerpt "$LOGS/lock-init-a.log")"
  quiet "$LOGS/lock-setup.log" tf "$a" rw apply -auto-approve -no-color || die "the first apply failed: $(excerpt "$LOGS/lock-setup.log")"
  quiet "$LOGS/lock-init-b.log" tf_init "$b" rw || die "tofu init failed: $(excerpt "$LOGS/lock-init-b.log")"
  say "$LOCK_ROUNDS rounds. In each, two applies start together; the winner holds the lock for $HOLD_SECONDS s."
  say "Exactly one must win, and no lock may be left behind. About $((LOCK_ROUNDS * (HOLD_SECONDS + 15) / 60 + 2)) minutes."
  for r in $(seq 1 "$LOCK_ROUNDS"); do
    ca=0; cb=0
    tf "$a" rw apply -auto-approve -no-color -lock-timeout=0s -var "round=$r" -var "hold_seconds=$HOLD_SECONDS" \
      >"$LOGS/lock-$r-a.log" 2>&1 & pa=$!
    tf "$b" rw apply -auto-approve -no-color -lock-timeout=0s -var "round=$r" -var "hold_seconds=$HOLD_SECONDS" \
      >"$LOGS/lock-$r-b.log" 2>&1 & pb=$!
    wait "$pa" || ca=$?
    wait "$pb" || cb=$?
    if [[ "$ca" == 0 && "$cb" == 0 ]]; then
      both=$((both + 1)); bad "round $r: BOTH applies succeeded"
    elif [[ "$ca" != 0 && "$cb" != 0 ]]; then
      neither=$((neither + 1)); bad "round $r: neither apply succeeded (a: $(excerpt "$LOGS/lock-$r-a.log"))"
    else
      if { [[ "$ca" != 0 ]] && lock_error "$LOGS/lock-$r-a.log"; } || { [[ "$cb" != 0 ]] && lock_error "$LOGS/lock-$r-b.log"; }; then
        one=$((one + 1)); ok "round $r: one won, the other was refused the lock"
      else
        odd=$((odd + 1)); bad "round $r: one won, the other failed for another reason (see $LOGS/lock-$r-*.log)"
      fi
    fi
    rc=0
    quiet "$LOGS/lock-$r-after.log" tf "$a" rw plan -no-color -lock-timeout=0s -var "round=$r" || rc=$?
    if [[ "$rc" != 0 ]] && lock_error "$LOGS/lock-$r-after.log"; then
      leftover=$((leftover + 1)); bad "round $r: a lock was left behind"
      id=$(sed -n 's/^ *ID: *//p' "$LOGS/lock-$r-after.log" | head -n 1)
      if [[ -n "$id" ]]; then
        quiet "$LOGS/lock-$r-unlock.log" tf "$a" rw force-unlock -force "$id" \
          || die "couldn't force-unlock $id; see $LOGS/lock-$r-unlock.log"
        note "cleared it with tofu force-unlock"
      fi
    fi
  done
  say "Last, the waiting path: a second apply with -lock-timeout=90s starts 6 s after the first."
  ca=0; cb=0; r=$((LOCK_ROUNDS + 1))
  tf "$a" rw apply -auto-approve -no-color -lock-timeout=0s -var "round=$r" -var "hold_seconds=$HOLD_SECONDS" \
    >"$LOGS/lock-wait-a.log" 2>&1 & pa=$!
  sleep 6
  quiet "$LOGS/lock-wait-b.log" tf "$b" rw apply -auto-approve -no-color -lock-timeout=90s -var "round=$r" -var "hold_seconds=0" || cb=$?
  wait "$pa" || ca=$?
  if [[ "$ca" == 0 && "$cb" == 0 ]]; then waiter="waited, then applied"; ok "the second apply waited and then applied"
  else waiter="failed (exits $ca, $cb)"; bad "the waiting apply failed: $(excerpt "$LOGS/lock-wait-b.log")"; fi
  unset TF_VAR_passphrase_primary
  summary="OpenTofu $TOFU_VERSION, $LOCK_ROUNDS simultaneous rounds: one winner in $one, both applied in $both, neither in $neither, other failures in $odd; locks left behind: $leftover. Second apply with -lock-timeout=90s: $waiter."
  if [[ "$both" -gt 0 || "$leftover" -gt 0 ]]; then
    conclude LOCK yes "use_lockfile is removed and every job runs -lock=false; the concurrency groups are the only guard (slices 1.4, 1.5), and the runbook gains ADR 0032's rule." "Fails. $summary"
  else
    conclude LOCK no "" "use_lockfile stays. $summary"
  fi
}
spike_lock
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Re-encrypt: which command rewrites an unchanged state (ADR 0027, ADR 0032)"
# reencrypt_shape SHAPE FIRST PRIMARY FALLBACK: write a state under the key
# provider FIRST with the old passphrase, rotate to PRIMARY (new passphrase)
# with FALLBACK (old), then climb ADR 0032's three commands. Sets RE_* vars.
RE_READ=""; RE_BASE=""; RE_CMD1=""; RE_CMD2=""; RE_CMD3=""; RE_WINNER=""; RE_OLD=""
reencrypt_shape() {
  local shape="$1" first="$2" primary="$3" fallback="$4"
  local key="reencrypt-$shape-$RUN/terraform.tfstate" main="$WORK/tofu/re-$shape" chk="$WORK/tofu/re-$shape-check"
  local old new rc f="$WORK/tofu/re-$shape-pulled.tfstate"
  old=$(openssl rand -hex 32); new=$(openssl rand -hex 32)
  RE_READ=""; RE_BASE="not run"; RE_CMD1="not run"; RE_CMD2="not run"; RE_CMD3="not run"; RE_WINNER="none"; RE_OLD="not run"
  rm -rf "$main" "$chk"
  track_key "$key"
  # Is the state readable by the new passphrase alone? A fresh directory that
  # knows only the new one pulls the state.
  new_alone() {
    rm -rf "$chk"; write_root "$chk" "$key" "$primary"
    quiet "$LOGS/re-$shape-check-init.log" tf_init "$chk" rw || return 1
    quiet "$LOGS/re-$shape-check-pull.log" tf "$chk" rw state pull
  }
  export TF_VAR_passphrase_primary="$old"
  write_root "$main" "$key" "$first"
  quiet "$LOGS/re-$shape-init.log" tf_init "$main" rw || die "tofu init failed: $(excerpt "$LOGS/re-$shape-init.log")"
  quiet "$LOGS/re-$shape-apply.log" tf "$main" rw apply -auto-approve -no-color || die "the first apply failed: $(excerpt "$LOGS/re-$shape-apply.log")"
  ok "a state exists, encrypted with the old passphrase under key provider '$first'"
  export TF_VAR_passphrase_primary="$new" TF_VAR_passphrase_fallback="$old"
  write_root "$main" "$key" "$primary" "$fallback"
  rc=0
  quiet "$LOGS/re-$shape-rot-init.log" tf_init "$main" rw || rc=$?
  if [[ "$rc" == 0 ]]; then quiet "$LOGS/re-$shape-rot-plan.log" tf "$main" rw plan -no-color -lock=false || rc=$?; fi
  if [[ "$rc" != 0 ]]; then
    RE_READ="FAILS: $(excerpt "$LOGS/re-$shape-rot-plan.log")$(excerpt "$LOGS/re-$shape-rot-init.log")"
    bad "with new='$primary' and fallback='$fallback', the state can't be read"
    unset TF_VAR_passphrase_primary TF_VAR_passphrase_fallback
    return 1
  fi
  RE_READ="ok"; ok "rotated: new passphrase under '$primary', old as fallback '$fallback'; a plan still reads the state"
  if new_alone; then RE_BASE="readable"; warn "the new passphrase alone already reads the state, before any command"
  else RE_BASE="not readable"; ok "baseline: the new passphrase alone can't read it yet"; fi

  rc=0; quiet "$LOGS/re-$shape-cmd1.log" tf "$main" rw apply -refresh-only -auto-approve -no-color || rc=$?
  if new_alone; then RE_CMD1="re-encrypts (exit $rc)"; RE_WINNER="tofu apply -refresh-only"; ok "1. tofu apply -refresh-only: re-encrypts"
  else RE_CMD1="doesn't (exit $rc)"; bad "1. tofu apply -refresh-only: doesn't"; fi

  if [[ "$RE_WINNER" == none ]]; then
    rc=0
    if tf "$main" rw state pull >"$f" 2>"$LOGS/re-$shape-cmd2-pull.log"; then
      quiet "$LOGS/re-$shape-cmd2.log" tf "$main" rw state push "$f" || rc=$?
    else rc=$?; fi
    rm -f "$f"
    if new_alone; then RE_CMD2="re-encrypts (exit $rc)"; RE_WINNER="tofu state pull, then tofu state push"; ok "2. tofu state pull + push: re-encrypts"
    else RE_CMD2="doesn't (exit $rc)"; bad "2. tofu state pull + push: doesn't"; fi
  fi

  if [[ "$RE_WINNER" == none ]]; then
    rc=0; quiet "$LOGS/re-$shape-cmd3.log" tf "$main" rw apply -auto-approve -no-color -var rotation_marker=2 || rc=$?
    if new_alone; then RE_CMD3="re-encrypts (exit $rc)"; RE_WINNER="an apply that raises the rotation marker"; ok "3. apply raising the rotation marker: re-encrypts"
    else RE_CMD3="doesn't (exit $rc)"; bad "3. apply raising the rotation marker: doesn't: $(excerpt "$LOGS/re-$shape-cmd3.log")"; fi
  fi

  # And the old passphrase alone must no longer read it.
  export TF_VAR_passphrase_primary="$old"
  rm -rf "$chk"; write_root "$chk" "$key" "$first"
  if quiet "$LOGS/re-$shape-old-init.log" tf_init "$chk" rw && quiet "$LOGS/re-$shape-old-pull.log" tf "$chk" rw state pull; then
    RE_OLD="still reads it"
  else RE_OLD="can't read it"; fi
  note "afterwards, the old passphrase alone $RE_OLD"
  unset TF_VAR_passphrase_primary TF_VAR_passphrase_fallback
  [[ "$RE_WINNER" != none ]]
}
spike_reenc() {
  need R2_RW_SECRET "Stage 4 hasn't saved the R2 keys yet; re-run the wizard to do it." || return 0
  begin R_REENC || return 0
  local shape_note="" a_read summary
  say "ADR 0027 keeps fixed names: the old passphrase moves to STATE_PASSPHRASE_PREVIOUS (the"
  say "fallback) and a new STATE_PASSPHRASE takes its place. OpenTofu's docs warn that"
  say "encrypted data records its key provider's name, so that shape is tried first."
  printf '\n'
  say "${BOLD}Shape A${RESET}: key providers 'current' and 'previous'; the old passphrase moves between them."
  if reencrypt_shape a current current previous; then
    shape_note="ADR 0027's shape works (fixed key provider names 'current' and 'previous', the old passphrase moving to the fallback)."
  else
    a_read="$RE_READ"
    if [[ "$RE_READ" == ok ]]; then
      shape_note="ADR 0027's shape reads through the fallback, but none of the three commands re-encrypted it."
    else
      shape_note="ADR 0027's shape does NOT work: with the old passphrase moved from key provider 'current' to 'previous', the state can't be read ($a_read). Each passphrase must keep its key provider's name for life (below: 'gen1' as fallback, 'gen2' new), so the committed encryption block changes on every rotation. (Giving both key providers one encrypted_metadata_alias is refused as a duplicate metadata key; checked on 1.13.1 with a local backend when this wizard was written.)"
      printf '\n'
      say "${BOLD}Shape B${RESET}: each passphrase keeps its own key provider name ('gen1' old, 'gen2' new), as the docs show."
      reencrypt_shape b gen1 gen2 gen1 || true
    fi
  fi
  summary="OpenTofu $TOFU_VERSION. $shape_note Fallback read: $RE_READ. New passphrase alone before any command: $RE_BASE. 1) apply -refresh-only: $RE_CMD1. 2) state pull + push: $RE_CMD2. 3) apply raising the rotation marker: $RE_CMD3. Afterwards the old passphrase alone $RE_OLD."
  if [[ "$RE_WINNER" == none ]]; then
    conclude REENC yes "No command re-encrypted the state, which ADR 0032 says can't happen; the rotation runbook can't be written until this is understood." "Unresolved. $summary"
  elif [[ "$shape_note" == *"does NOT work"* ]]; then
    conclude REENC yes "reencrypt runs: $RE_WINNER. But ADR 0027's STATE_PASSPHRASE / STATE_PASSPHRASE_PREVIOUS shape needs redesigning (the rotation runbook, and every root's encryption block)." "reencrypt runs: $RE_WINNER. $summary"
  else
    conclude REENC no "" "reencrypt runs: $RE_WINNER. $summary"
  fi
}
spike_reenc
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Durable Object location: can an object learn where it is? (ADR 0017)"
spike_do() {
  begin R_DO || return 0
  local dir="$WORK/links-data" url i hint line table="" props="" distinct worker_colo="?" away=0
  say "This deploys ${BOLD}$LD_WORKER${RESET}, a stand-in for links-data: a SQLite Durable Object class"
  say "declared with 'exports', a '$WORKFLOW_NAME' Workflow, and a keyed workers.dev route."
  say "Stages 10 to 12 reuse it."
  confirm "Deploy it?" || return 0
  write_ld_worker
  loud "$LOGS/ld-deploy.log" wr "$CF_SETUP_TOKEN" "$dir" deploy || die "the deploy failed; see above."
  url=$(grep -oE 'https://[A-Za-z0-9.-]+\.workers\.dev' "$LOGS/ld-deploy.log" | tail -n 1 || true)
  if [[ -z "$url" ]]; then ask LD_URL "Paste the workers.dev URL Wrangler printed:"; url="$LD_URL"; fi
  [[ "$url" == https://*.workers.dev* ]] || die "that isn't a workers.dev URL."
  url="${url%/}"; LD_URL="$url"
  write_env LD_URL "$url"
  record WORKERS_SUBDOMAIN "$(sed -E 's#https://[^.]+\.([^.]+)\.workers\.dev.*#\1#' <<<"$url")"
  record LD_DEPLOYED yes
  # A fresh workers.dev subdomain can take minutes to resolve; wait for a 200.
  say "Waiting for $url to answer (a new workers.dev subdomain can take a few minutes)..."
  for i in $(seq 1 60); do
    if probe "$url/?k=$SPIKE_KEY&hint=weur&name=ready-$RUN" && [[ "$PROBE_STATUS" == 200 || "$PROBE_STATUS" == 403 ]]; then break; fi
    sleep 5
  done
  if [[ "$PROBE_STATUS" != 200 ]]; then
    bad "still no 200 after five minutes: HTTP ${PROBE_STATUS:-none}; the reply is in $LOGS/ld-probe.log"
    note "$(excerpt "$LOGS/ld-probe.log")"
    note "Try it yourself: curl -i '$url/?k=<SPIKE_KEY from state.env>&hint=weur&name=x'"
    note "A 403 means the key differs; an HTML error page means the Worker threw; nothing means DNS."
    confirm "Carry on probing anyway?" || die "re-run the wizard once the URL answers; the deploy is kept."
  fi
  say "Asking five new objects, each created with a different location hint, where they are."
  say "Each fetches cloudflare.com/cdn-cgi/trace from inside the object and reports its 'colo'."
  printf '\n'
  printf '  %s%-6s %-12s %-12s %-22s%s\n' "$BOLD" "hint" "object says" "trace loc" "Worker ran in" "$RESET"
  for hint in wnam enam weur apac oc; do
    line=""
    for i in 1 2 3; do
      if probe "$url/?k=$SPIKE_KEY&hint=$hint&name=direct-$hint-$RUN-$i" && jq -e . "$PROBE_BODY" >/dev/null 2>&1; then
        line=$(cat "$PROBE_BODY"); break
      fi
      sleep 3
    done
    if [[ -z "$line" ]]; then
      bad "$hint: no JSON came back (HTTP ${PROBE_STATUS:-none}; reply kept in $LOGS/ld-probe.log)"
      table+="${hint}→error "; continue
    fi
    worker_colo=$(jq -r '.worker_colo // "?"' <<<"$line")
    printf '  %-6s %-12s %-12s %-22s\n' "$hint" "$(jq -r '.trace_colo // .trace_error // "none"' <<<"$line")" \
      "$(jq -r '.trace_loc // "-"' <<<"$line")" "$worker_colo"
    table+="${hint}→$(jq -r '.trace_colo // "none"' <<<"$line") "
    if [[ "$(jq -r '.trace_colo // ""' <<<"$line")" != "$worker_colo" ]]; then away=$((away + 1)); fi
    props=$(jq -r '"ctx: " + (.ctx_properties | join(",")) + "; ctx.id: " + (.id_properties | join(","))' <<<"$line")
  done
  distinct=$(tr ' ' '\n' <<<"$table" | sed -n 's/.*→//p' | grep -vE '^(none|error)$' | sort -u | wc -l | tr -d ' ')
  printf '\n'
  note "Properties on the object's own context (nothing documented names a place):"
  note "$props"
  printf '\n'
  say "Colos are airport codes. The method works if each object's colo sits in its hint's region"
  say "(wnam: western North America, enam: eastern, weur: western Europe, apac: Asia-Pacific,"
  say "oc: Oceania), and not simply wherever the Worker ran ($worker_colo)."
  note "$distinct distinct colo(s); $away of 5 differ from the Worker's own."
  ask DO_NOTE "Optional note (anything odd, or a context property that names a place):"
  if confirm "Do the colos match their hints?"; then
    conclude DO no "" "A Durable Object learns its colo by fetching https://www.cloudflare.com/cdn-cgi/trace from inside itself and reading 'colo='. Objects created with five hints reported: $table(Worker ran in $worker_colo). Context properties: $props. ${DO_NOTE:+Note: $DO_NOTE}"
  else
    conclude DO yes "The touch step reports only that each shard answered (slice 1.5)." "No method found. cdn-cgi/trace from inside the object reported: $table(Worker ran in $worker_colo), which doesn't track the hints. Context properties: $props. ${DO_NOTE:+Note: $DO_NOTE}"
  fi
}
spike_do
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Create the two role tokens ADR 0024 describes"
role_tokens() {
  need LD_DEPLOYED "Stage 8 hasn't deployed $LD_WORKER yet; the tokens are scoped to it. Re-run the wizard." || return 0
  if [[ -n "$CF_ADMIN_TOKEN" && -n "$CF_PLAN_TOKEN" ]]; then
    ok "both role tokens are already saved"
    confirm "Enter them again?" || return 0
  fi
  say "Stages 10 and 11 ask what ADR 0024's roles can do, so they need tokens with exactly"
  say "those roles. Per-Worker roles exist only on account-owned tokens (shipped 2026-09-15)."
  open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/home"
  step "${BOLD}Manage Account → Account API Tokens → Create Token${RESET}."
  step "Token 1, the production-admin role: name ${BOLD}$PREFIX-admin${RESET}, scope ${BOLD}Specified Workers${RESET},"
  step "    select ${BOLD}$LD_WORKER${RESET}, role ${BOLD}Editor${RESET}. Nothing else. Expire in a week."
  ask_secret CF_ADMIN_TOKEN "Paste the $PREFIX-admin token:"
  step "Token 2, the production-plan role: name ${BOLD}$PREFIX-plan${RESET}, scope ${BOLD}Specified Workers${RESET},"
  step "    select ${BOLD}$LD_WORKER${RESET}, role ${BOLD}Metadata Read-Only${RESET}. Nothing else."
  ask_secret CF_PLAN_TOKEN "Paste the $PREFIX-plan token:"
  [[ -n "$CF_ADMIN_TOKEN" && -n "$CF_PLAN_TOKEN" ]] || die "both tokens are required."
  [[ "$CF_ADMIN_TOKEN" != "$CF_PLAN_TOKEN" ]] || die "the two tokens are the same one."
  token_ok "$CF_ADMIN_TOKEN" || die "Cloudflare doesn't accept the admin token (HTTP $CF_STATUS: $(cf_error))."
  token_ok "$CF_PLAN_TOKEN" || die "Cloudflare doesn't accept the plan token (HTTP $CF_STATUS: $(cf_error))."
  ok "both tokens are active"
  write_env CF_ADMIN_TOKEN "$CF_ADMIN_TOKEN"; write_env CF_PLAN_TOKEN "$CF_PLAN_TOKEN"
  note "This screen is new. If its labels differ from the ones above, say how:"
  ask ROLE_TOKEN_NOTE "Optional note on what the token screen actually offered:"
  write_env ROLE_TOKEN_NOTE "$ROLE_TOKEN_NOTE"
}
role_tokens
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Workflows: can Editor on the Worker start and read an instance? (ADR 0031)"
# wf_try TOKEN: create an instance and poll it. Sets WF_CREATE, WF_READ, WF_FINAL, WF_OUT.
WF_CREATE=""; WF_READ=""; WF_FINAL=""; WF_OUT=""; WF_ERR=""
wf_try() {
  local token="$1" id i
  WF_READ="not tried"; WF_FINAL="not reached"; WF_OUT=""; WF_ERR=""
  cf "$token" POST "/accounts/$CF_ACCOUNT_ID/workflows/$WORKFLOW_NAME/instances" '{}'
  WF_CREATE="$CF_STATUS"
  id=$(jq -r '.result.id // empty' "$CF_BODY" 2>/dev/null || true)
  if [[ "$CF_STATUS" != 2* || -z "$id" ]]; then WF_ERR=$(cf_error); return 1; fi
  for i in $(seq 1 60); do
    cf "$token" GET "/accounts/$CF_ACCOUNT_ID/workflows/$WORKFLOW_NAME/instances/$id"
    WF_READ="$CF_STATUS"
    if [[ "$CF_STATUS" != 2* ]]; then WF_ERR=$(cf_error); return 1; fi
    WF_FINAL=$(jq -r '.result.status // "unknown"' "$CF_BODY")
    case "$WF_FINAL" in complete|errored|terminated) break ;; esac
    sleep 3
  done
  WF_OUT=$(jq -r '[.result.output[]? | "\(.hint)→\(.trace_colo // "none")"] | join(" ")' "$CF_BODY" 2>/dev/null || true)
  [[ "$WF_FINAL" == complete ]]
}
spike_wf() {
  need CF_ADMIN_TOKEN "Stage 9 hasn't saved the role tokens yet; re-run the wizard to do it." || return 0
  begin R_WF || return 0
  local first added="" tries=0
  say "With the $PREFIX-admin token (Editor on $LD_WORKER only), the wizard starts one"
  say "'$WORKFLOW_NAME' instance over the Workflows REST API and polls it until it ends."
  if wf_try "$CF_ADMIN_TOKEN"; then
    ok "created (HTTP $WF_CREATE), read (HTTP $WF_READ), ended '$WF_FINAL'"
    [[ -z "$WF_OUT" ]] || note "the Workflow's placement report: $WF_OUT"
    conclude WF no "" "Editor on the Worker is enough: create instance HTTP $WF_CREATE, get instance HTTP $WF_READ, final status '$WF_FINAL'. ${WF_OUT:+Placement report from inside the Workflow: $WF_OUT.} ${ROLE_TOKEN_NOTE:+Token screen note: $ROLE_TOKEN_NOTE}"
    return 0
  fi
  first="create HTTP $WF_CREATE, get HTTP $WF_READ, final '$WF_FINAL'${WF_ERR:+, error: $WF_ERR}"
  bad "with Editor alone: $first"
  say "Control: the same calls with the setup token, to prove the Workflow itself works."
  if wf_try "$CF_SETUP_TOKEN"; then ok "the setup token can (final '$WF_FINAL'), so this is a permissions answer"
  else
    warn "The setup token fails too (create HTTP $WF_CREATE, get HTTP $WF_READ, final '$WF_FINAL' $WF_ERR)."
    warn "That is a broken Workflow or endpoint, not a permissions answer. Nothing recorded; look at"
    warn "the Workflow in the dashboard, then run this stage again."
    return 0
  fi
  say "Now find the narrowest permission that fixes it. Edit the ${BOLD}$PREFIX-admin${RESET} token:"
  open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/home"
  step "Manage Account → Account API Tokens → $PREFIX-admin → Edit."
  step "Add ONE permission, the narrowest that names Workflows. If none does, the documented"
  step "one for creating an instance is the account permission 'Workers Scripts: Edit'."
  while :; do
    tries=$((tries + 1))
    ask WF_ADDED "What did you add (exactly as the dashboard names it)? Empty to give up:"
    if [[ -z "$WF_ADDED" ]]; then break; fi
    added="$WF_ADDED"
    sleep 5
    if wf_try "$CF_ADMIN_TOKEN"; then ok "with '$added': created, read, ended '$WF_FINAL'"; break; fi
    bad "still failing with '$added': create HTTP $WF_CREATE, get HTTP $WF_READ $WF_ERR"
    added=""
    step "Remove that one and try another, or leave the answer empty to give up."
    [[ "$tries" -lt 6 ]] || break
  done
  if [[ -n "$added" ]]; then
    conclude WF yes "production-admin gains '$added', and ADR 0024's table says so (slices 1.4, 1.5)." "Editor on the Worker is not enough ($first). With '$added' added: create HTTP $WF_CREATE, get HTTP $WF_READ, final '$WF_FINAL'. ${ROLE_TOKEN_NOTE:+Token screen note: $ROLE_TOKEN_NOTE}"
  else
    conclude WF yes "production-admin needs a Workflows permission that this spike didn't find; settle it before slice 1.4." "Editor on the Worker is not enough ($first), and no added permission was found to fix it."
  fi
}
spike_wf
pause

# ── 11 ────────────────────────────────────────────────────────────────────
stage "The tag: deploy --tag with exports, read it back, versions upload (ADR 0031)"
spike_tag() {
  need CF_PLAN_TOKEN "Stage 9 hasn't saved the role tokens yet; re-run the wizard to do it." || return 0
  begin R_TAG || return 0
  local dir="$WORK/links-data" tag tag2 rc deploy_by="the Editor token" vid found="" probes="" p hit upload
  tag=$(openssl rand -hex 32); tag2=$(openssl rand -hex 32)
  write_ld_worker
  say "Deploying $LD_WORKER with --tag <64 hex characters>, as the $PREFIX-admin (Editor) token:"
  rc=0; loud "$LOGS/tag-deploy.log" wr "$CF_ADMIN_TOKEN" "$dir" deploy --tag "$tag" --message "spike $ISSUE_NUMBER tag" || rc=$?
  if [[ "$rc" != 0 ]]; then
    bad "the Editor token couldn't deploy: $(excerpt "$LOGS/tag-deploy.log")"
    deploy_by="the setup token (the Editor token's deploy failed: $(excerpt "$LOGS/tag-deploy.log"))"
    rc=0; loud "$LOGS/tag-deploy-setup.log" wr "$CF_SETUP_TOKEN" "$dir" deploy --tag "$tag" --message "spike $ISSUE_NUMBER tag" || rc=$?
    if [[ "$rc" != 0 ]]; then
      conclude TAG yes "plan reads the bundle hash from the GitHub deployment record (slice 1.5)." "wrangler $WRANGLER_VERSION deploy --tag failed on a Worker with exports: $(excerpt "$LOGS/tag-deploy-setup.log")"
      return 0
    fi
    cp "$LOGS/tag-deploy-setup.log" "$LOGS/tag-deploy.log"
  fi
  ok "deployed with the tag"
  vid=$(grep -i 'version id' "$LOGS/tag-deploy.log" | grep -oE '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | tail -n 1 || true)
  say "Reading it back with the $PREFIX-plan token (Metadata Read-Only), every way there is:"
  # probe LABEL PATH: one GET with the plan token; does the body hold the tag?
  probe() {
    cf "$CF_PLAN_TOKEN" GET "$2"
    if grep -q "$tag" "$CF_BODY" 2>/dev/null; then hit="tag found"; [[ -n "$found" ]] || found="$1"
    else hit="no tag"; fi
    if [[ "$hit" == "tag found" ]]; then ok "$1: HTTP $CF_STATUS, $hit"; else bad "$1: HTTP $CF_STATUS, $hit $(cf_error)"; fi
    probes+="$1: HTTP $CF_STATUS, $hit. "
  }
  probe "GET /workers/scripts/{name}/versions" "/accounts/$CF_ACCOUNT_ID/workers/scripts/$LD_WORKER/versions"
  if [[ -n "$vid" ]]; then
    probe "GET /workers/scripts/{name}/versions/{id}" "/accounts/$CF_ACCOUNT_ID/workers/scripts/$LD_WORKER/versions/$vid"
  fi
  probe "GET /workers/scripts/{name}/deployments" "/accounts/$CF_ACCOUNT_ID/workers/scripts/$LD_WORKER/deployments"
  probe "GET /workers/workers/{name}/versions (beta API, name used as the id)" "/accounts/$CF_ACCOUNT_ID/workers/workers/$LD_WORKER/versions"
  for p in "versions list --json" "versions view ${vid:-none} --json" "deployments status --json"; do
    [[ "$p" != *none* ]] || continue
    rc=0
    # shellcheck disable=SC2086
    quiet "$LOGS/tag-cli.log" wr "$CF_PLAN_TOKEN" "$dir" $p || rc=$?
    if grep -q "$tag" "$LOGS/tag-cli.log"; then hit="tag found"; [[ -n "$found" ]] || found="wrangler ${p%% --json}"; ok "wrangler $p: exit $rc, $hit"
    else hit="no tag"; bad "wrangler $p: exit $rc, $hit"; fi
    probes+="wrangler $p: exit $rc, $hit. "
  done
  say "And wrangler versions upload on the same config, with the setup token:"
  rc=0; loud "$LOGS/tag-upload.log" wr "$CF_SETUP_TOKEN" "$dir" versions upload --tag "$tag2" --message "spike $ISSUE_NUMBER upload" || rc=$?
  if [[ "$rc" == 0 ]]; then upload="succeeds (exit 0)"; else upload="fails (exit $rc): $(excerpt "$LOGS/tag-upload.log")"; fi
  note "versions upload $upload"
  if [[ -n "$found" ]]; then
    conclude TAG no "" "wrangler $WRANGLER_VERSION deploy --tag works on a Worker with exports (deployed by $deploy_by). The Metadata Read-Only token reads the tag back; first hit: $found. All probes: $probes wrangler versions upload on the same config $upload"
  else
    conclude TAG yes "plan reads the bundle hash from the GitHub deployment record (slice 1.5)." "wrangler $WRANGLER_VERSION deploy --tag ran (by $deploy_by), but the Metadata Read-Only token can't read the tag back. Probes: $probes wrangler versions upload on the same config $upload"
  fi
}
spike_tag
pause

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Does --secrets-file remove a hand-set secret? (ADR 0032, ADR 0016)"
spike_secrets() {
  need LD_DEPLOYED "Stage 8 hasn't deployed $LD_WORKER yet; re-run the wizard to do it." || return 0
  begin R_SECRETS || return 0
  local dir="$WORK/links-data" before after rc file="$WORK/links-data/ci-secrets.json" has_hand has_ci
  names() { jq -r '[.[].name] | sort | join(",")' 2>/dev/null || true; }
  write_ld_worker
  say "On $LD_WORKER: set HAND_SET_SECRET by hand, then deploy with a --secrets-file that names"
  say "only CI_SECRET, and list the secrets."
  openssl rand -hex 16 | wr "$CF_SETUP_TOKEN" "$dir" secret put HAND_SET_SECRET >"$LOGS/secrets-put.log" 2>&1 \
    || die "wrangler secret put failed: $(excerpt "$LOGS/secrets-put.log")"
  before=$(wr "$CF_SETUP_TOKEN" "$dir" secret list --format json 2>/dev/null | names) || true
  [[ ",$before," == *,HAND_SET_SECRET,* ]] || die "HAND_SET_SECRET isn't listed after the put (listed: ${before:-nothing})."
  ok "before: $before"
  printf '{ "CI_SECRET": "%s" }\n' "$(openssl rand -hex 16)" >"$file"
  rc=0; loud "$LOGS/secrets-deploy.log" wr "$CF_SETUP_TOKEN" "$dir" deploy --secrets-file "$file" || rc=$?
  rm -f "$file"
  [[ "$rc" == 0 ]] || die "the deploy with --secrets-file failed; see above."
  after=$(wr "$CF_SETUP_TOKEN" "$dir" secret list --format json 2>/dev/null | names) || true
  say "after:  ${BOLD}${after:-nothing}${RESET}"
  has_hand=no; has_ci=no
  [[ ",$after," != *,HAND_SET_SECRET,* ]] || has_hand=yes
  [[ ",$after," != *,CI_SECRET,* ]] || has_ci=yes
  if [[ "$has_ci" != yes ]]; then
    warn "CI_SECRET isn't listed, so the flag didn't do what the spike assumes. Nothing recorded."
    return 0
  fi
  if [[ "$has_hand" == yes ]]; then
    conclude SECRETS no "" "The hand-set secret survives. wrangler $WRANGLER_VERSION, Worker with exports: secrets before '$before'; after a deploy with --secrets-file naming only CI_SECRET: '$after'. links-data deploys with --secrets-file."
  else
    conclude SECRETS yes "links-data deploys without --secrets-file and the admin job pushes its CI-held secrets with wrangler secret bulk (slice 1.5)." "The hand-set secret is REMOVED. wrangler $WRANGLER_VERSION: secrets before '$before'; after a deploy with --secrets-file naming only CI_SECRET: '$after'."
  fi
}
spike_secrets
pause

# ── 13 ────────────────────────────────────────────────────────────────────
stage "Deployment records and retention: set up (ADR 0027)"
ret_workflow() {
  cat <<'YAML'
name: deploy-record

on: workflow_dispatch

permissions:
  contents: read
  deployments: write

jobs:
  record:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Write a deployment record, as a preview run will
        run: |
          id=$(gh api -X POST "repos/$GITHUB_REPOSITORY/deployments" --input - --jq .id <<EOF
          {"ref":"$GITHUB_SHA","environment":"previews","auto_merge":false,
           "required_contexts":[],"transient_environment":true,"production_environment":false,
           "payload":{"pull_request":1,"head_sha":"$GITHUB_SHA","run_id":"$GITHUB_RUN_ID"}}
          EOF
          )
          gh api -X POST "repos/$GITHUB_REPOSITORY/deployments/$id/statuses" \
            -f state=success -F auto_inactive=false \
            -f log_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >/dev/null
          echo "SPIKE-RESULT deployment_id=$id run_id=$GITHUB_RUN_ID"
YAML
}
spike_ret_setup() {
  begin RET_RUN_ID || return 0
  local days before id="" i marker dep
  say "This creates the public repo ${BOLD}$RET_REPO${RESET}, sets its retention to 1 day, and runs a"
  say "workflow that writes a deployment record in environment 'previews'. Stage 17 looks, a day"
  say "or more later, at whether the record is still there once GitHub has deleted the run."
  confirm "Create $RET_REPO and run the workflow (as $GH_LOGIN)?" || return 0
  ensure_workflow_scope
  ensure_repo "$RET_REPO" "Throwaway: $ISSUE_REPO#$ISSUE_NUMBER deployment record retention spike"
  # Retention applies only to runs made after it is set, so set it first.
  gh api -X PUT "repos/$RET_REPO/actions/permissions/artifact-and-log-retention" -F days=1 >/dev/null \
    || die "couldn't set the retention period."
  days=$(gh api "repos/$RET_REPO/actions/permissions/artifact-and-log-retention" --jq .days)
  [[ "$days" == 1 ]] || die "retention reads back as $days days, not 1."
  ok "retention is 1 day"
  commit_file "$RET_REPO" ".github/workflows/deploy-record.yml" "$(ret_workflow)" >/dev/null
  ok "wrote the workflow"
  before=$(gh run list -R "$RET_REPO" --workflow deploy-record.yml -L 1 --json databaseId --jq '.[0].databaseId // 0' 2>/dev/null) || before=0
  for i in 1 2 3 4 5 6 7 8 9 10; do
    if gh workflow run deploy-record.yml -R "$RET_REPO" >/dev/null 2>&1; then break; fi
    [[ "$i" != 10 ]] || die "couldn't dispatch the workflow in $RET_REPO."
    sleep 3
  done
  for i in $(seq 1 30); do
    sleep 2
    id=$(gh run list -R "$RET_REPO" --workflow deploy-record.yml -L 1 --json databaseId --jq '.[0].databaseId // 0' 2>/dev/null) || id=0
    if [[ -n "$id" && "$id" != 0 && "$id" != "${before:-0}" ]]; then break; fi
    id=""
  done
  [[ -n "$id" ]] || die "no run appeared; look at https://github.com/$RET_REPO/actions"
  gh run watch "$id" -R "$RET_REPO" --exit-status >/dev/null 2>&1 || true
  marker=""
  for i in 1 2 3 4 5; do
    marker=$(gh run view "$id" -R "$RET_REPO" --log 2>/dev/null | grep -o 'SPIKE-RESULT deployment_id=[0-9]* run_id=[0-9]*' | tail -n 1) || marker=""
    [[ -z "$marker" ]] || break
    sleep 3
  done
  [[ -n "$marker" ]] || die "the run didn't write a deployment record; see https://github.com/$RET_REPO/actions/runs/$id"
  dep=$(sed -E 's/.*deployment_id=([0-9]+).*/\1/' <<<"$marker")
  gh api "repos/$RET_REPO/deployments/$dep" --jq .id >/dev/null || die "deployment $dep can't be read back."
  ok "run $id wrote deployment record $dep"
  record RET_DEPLOYMENT_ID "$dep"
  record RET_AT "$(date -u +%Y-%m-%dT%H:%MZ)"
  record RET_EPOCH "$(date +%s)"
  record RET_RUN_ID "$id"
  note "Come back after $(day_offset +1) or later; GitHub doesn't say when its sweep runs."
}
spike_ret_setup
pause

# ── 14 ────────────────────────────────────────────────────────────────────
stage "Dependabot and a main SHA pin: set up (ADR 0016)"
dbot_source_workflow() {
  cat <<YAML
# revision $1
name: noop
on:
  workflow_call:
permissions: {}
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "revision $1"
YAML
}
spike_dbot_setup() {
  begin DBOT_SETUP || return 0
  local c repo c1 c2 c3 pin consumer_wf
  say "Four public repos under ${BOLD}$GH_LOGIN${RESET}. Three hold a reusable workflow with three commits on"
  say "main (C1, C2, C3), and differ only in tags and in which commit the consumer pins:"
  step "$PREFIX-dbot-src-notag      no tags; the pin is C1"
  step "$PREFIX-dbot-src-tagbehind  v1.0.0 on C1; the pin is C2, ahead of the tag"
  step "$PREFIX-dbot-src-tagged     v1.0.0 on C2; the pin is C2, the tagged commit; main is ahead"
  step "$DBOT_CONSUMER_NAME      pins all three by SHA, with a daily github-actions dependabot.yml"
  note "Commits and tags are backdated a month: Dependabot's default 3-day cooldown would"
  note "otherwise hide every bump from a repo made today."
  confirm "Create the four repos (as $GH_LOGIN)?" || return 0
  ensure_workflow_scope
  for c in $DBOT_CASES; do
    if gh repo view "$GH_LOGIN/$PREFIX-dbot-src-$c" >/dev/null 2>&1; then
      die "$GH_LOGIN/$PREFIX-dbot-src-$c already exists; its commits and tag can't be redone in place. Delete the $PREFIX-dbot-* repos first (gh repo delete <repo> --yes), then re-run."
    fi
  done
  consumer_wf=$'name: pinned\non: workflow_dispatch\npermissions: {}\njobs:'
  for c in $DBOT_CASES; do
    repo="$GH_LOGIN/$PREFIX-dbot-src-$c"
    ensure_repo "$repo" "Throwaway: $ISSUE_REPO#$ISSUE_NUMBER Dependabot SHA pin spike (source: $c)"
    c1=$(commit_file "$repo" ".github/workflows/noop.yml" "$(dbot_source_workflow 1)" "$(days_ago 30)")
    c2=$(commit_file "$repo" ".github/workflows/noop.yml" "$(dbot_source_workflow 2)" "$(days_ago 20)")
    c3=$(commit_file "$repo" ".github/workflows/noop.yml" "$(dbot_source_workflow 3)" "$(days_ago 10)")
    case "$c" in
      notag)     pin="$c1" ;;
      tagbehind) pin="$c2"; gh api -X POST "repos/$repo/git/refs" -f ref=refs/tags/v1.0.0 -f "sha=$c1" >/dev/null || die "couldn't tag $repo." ;;
      tagged)    pin="$c2"; gh api -X POST "repos/$repo/git/refs" -f ref=refs/tags/v1.0.0 -f "sha=$c2" >/dev/null || die "couldn't tag $repo." ;;
    esac
    record "DBOT_${c}_PIN" "$pin"; record "DBOT_${c}_HEAD" "$c3"
    ok "$repo: pin ${pin:0:7}, main ${c3:0:7}"
    consumer_wf+=$'\n'"  $c:"$'\n'"    uses: $repo/.github/workflows/noop.yml@$pin"
  done
  ensure_repo "$DBOT_CONSUMER" "Throwaway: $ISSUE_REPO#$ISSUE_NUMBER Dependabot SHA pin spike (consumer)"
  commit_file "$DBOT_CONSUMER" ".github/workflows/pinned.yml" "$consumer_wf" >/dev/null
  commit_file "$DBOT_CONSUMER" ".github/dependabot.yml" $'version: 2\nupdates:\n  - package-ecosystem: "github-actions"\n    directory: "/"\n    schedule:\n      interval: "daily"' >/dev/null
  ok "wrote the pins and dependabot.yml to $DBOT_CONSUMER"
  record DBOT_AT "$(date -u +%Y-%m-%dT%H:%MZ)"
  record DBOT_SETUP yes
  say "Committing dependabot.yml normally starts a first update job within minutes. If none shows:"
  open_url "https://github.com/$DBOT_CONSUMER/network/updates"
  step "That page is Insights → Dependency graph → Dependabot. Next to .github/workflows,"
  step "open ${BOLD}Recent update jobs${RESET} and click ${BOLD}Check for updates${RESET}."
  note "Stage 16 reads the result once a job has finished."
}
spike_dbot_setup
pause

# ── 15 ────────────────────────────────────────────────────────────────────
stage "KV cached reads: analytics and the bill (ADR 0006)"
spike_kv_read() {
  need KV_READS_SENT "Stage 3 hasn't run the reads yet; re-run the wizard to do it." || return 0
  begin R_KV || return 0
  local sent date at analytics payload query billed_note suggestion
  load KV_DATE KV_AT KV_SECONDS KV_COLOS
  sent=$(get KV_READS_SENT); date="$KV_DATE"; at="$KV_AT"
  say "On $date at $at UTC the wizard made ${BOLD}$sent${RESET} reads of one key, from $KV_COLOS."
  # shellcheck disable=SC2016
  query='query Kv($accountTag: string!, $namespaceId: string, $start: Date, $end: Date) { viewer { accounts(filter: { accountTag: $accountTag }) { kvOperationsAdaptiveGroups(filter: { namespaceId: $namespaceId, date_geq: $start, date_leq: $end, actionType: "read" }, limit: 10000) { sum { requests } dimensions { actionType } } } } }'
  while :; do
    payload=$(jq -n --arg q "$query" --arg a "$CF_ACCOUNT_ID" --arg n "$KV_NAMESPACE_ID" --arg s "$date" --arg e "$(date -u +%Y-%m-%d)" \
      '{query: $q, variables: {accountTag: $a, namespaceId: $n, start: $s, end: $e}}')
    cf "$CF_SETUP_TOKEN" POST "/graphql" "$payload"
    if [[ "$CF_STATUS" == 200 ]] && jq -e '.errors == null' "$CF_BODY" >/dev/null 2>&1; then
      analytics=$(jq '[.. | .sum? | .requests? | numbers] | add // 0' "$CF_BODY")
      say "KV analytics (GraphQL, this namespace, reads since $date): ${BOLD}$analytics${RESET}"
    else
      analytics="unavailable"
      bad "the GraphQL query failed (HTTP $CF_STATUS): $(jq -c '.errors' "$CF_BODY" 2>/dev/null | cut -c1-300 | scrub)"
    fi
    confirm "Query again (analytics can lag a few minutes)?" || break
  done
  note "The same figure is in the dashboard: Workers KV → $KV_WORKER → Metrics."
  printf '\n'
  say "Now the billed figure, which only you can read and which can arrive a day late."
  open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/billing/billable-usage"
  step "That is ${BOLD}Manage Account → Billing → Billable Usage${RESET}. Find Workers KV reads for $date."
  step "If other KV namespaces on this account were read that day, subtract them or say so in the note."
  note "The page exists only on pay-as-you-go accounts. If it isn't there, answer 'unavailable'."
  if ! confirm "Is the usage for $date showing yet?"; then
    note "Nothing recorded. Re-run the wizard tomorrow; it comes straight back here."
    return 0
  fi
  ask KV_BILLED "KV reads the billing page counts for $date (a number, or 'unavailable'):"
  ask KV_BILLED_NOTE "Note (the exact label of the figure, other KV traffic that day, anything odd):"
  [[ -n "$KV_BILLED" ]] || KV_BILLED="unavailable"
  write_env KV_BILLED "$KV_BILLED"
  billed_note="Read count: $sent (one key, cacheTtl 30, burst of $KV_SECONDS s, colos: $KV_COLOS, $date $at UTC). KV analytics: $analytics. Billed usage: $KV_BILLED. ${KV_BILLED_NOTE:+Note: $KV_BILLED_NOTE}"
  if [[ "$KV_BILLED" =~ ^[0-9]+$ ]] && (( KV_BILLED * 10 >= sent * 9 )); then
    suggestion=billed
  elif [[ "$KV_BILLED" =~ ^[0-9]+$ ]] && (( KV_BILLED * 10 <= sent )); then
    suggestion="not billed"
  else
    suggestion=unknown
  fi
  say "On those figures the answer looks like: ${BOLD}$suggestion${RESET}."
  note "ADR 0006: 'billed' or 'unknown' keeps the per-colo cache; only a proven 'not billed' drops it."
  if [[ "$suggestion" == "not billed" ]] && confirm "Record 'proven not billed'?"; then
    conclude KV yes "Slice 5.1 (the per-colo cache and the colo-hit outcome) is dropped, and the delete bound becomes about 30 s (M5)." "Cached reads are NOT billed. $billed_note"
  elif [[ "$suggestion" == billed ]]; then
    conclude KV no "" "Cached reads are billed; the per-colo cache stays. $billed_note"
  else
    conclude KV no "" "Still unknown, so the per-colo cache stays as specified. $billed_note"
  fi
}
spike_kv_read
pause

# ── 16 ────────────────────────────────────────────────────────────────────
stage "Dependabot and a main SHA pin: read the result (ADR 0016)"
spike_dbot_read() {
  need DBOT_SETUP "Stage 14 hasn't created the repos yet; re-run the wizard to do it." || return 0
  begin R_DBOT || return 0
  local prs n diff c pin head out new summary="" stalled=no notag_out="" tagged_out="" behind_out=""
  open_url "https://github.com/$DBOT_CONSUMER/network/updates"
  step "Open ${BOLD}Recent update jobs${RESET} next to .github/workflows. If there is no finished job,"
  step "click ${BOLD}Check for updates${RESET} and wait for it."
  if ! confirm "Has an update job finished?"; then
    note "Nothing recorded. Re-run the wizard later; it comes straight back here."
    return 0
  fi
  prs=$(gh pr list -R "$DBOT_CONSUMER" --state all --json number --jq '.[].number' 2>/dev/null || true)
  for c in $DBOT_CASES; do
    pin=$(get "DBOT_${c}_PIN"); head=$(get "DBOT_${c}_HEAD"); out="no pull request"
    for n in $prs; do
      diff=$(gh pr diff "$n" -R "$DBOT_CONSUMER" 2>/dev/null || true)
      new=$(grep -E "^\+.*$PREFIX-dbot-src-$c/" <<<"$diff" | grep -oE '@[0-9a-f]{40}' | tr -d '@' | head -n 1 || true)
      [[ -n "$new" ]] || continue
      if [[ "$new" == "$head" ]]; then out="bumped to main's HEAD (PR #$n)"
      else out="bumped to ${new:0:7}, which is not main's HEAD ${head:0:7} (PR #$n)"; fi
      break
    done
    case "$c" in
      notag)     notag_out="$out";  say "No version tag, pin behind main:           ${BOLD}$out${RESET}" ;;
      tagbehind) behind_out="$out"; say "Tag behind the pin, pin behind main:       ${BOLD}$out${RESET}" ;;
      tagged)    tagged_out="$out"; say "Pin on the tagged commit, main ahead:      ${BOLD}$out${RESET}" ;;
    esac
  done
  step "In the job's log ('view logs'), look for why a pin was left alone, e.g. a cooldown line."
  ask DBOT_NOTE "Note from the job log (optional):"
  summary="Reusable-workflow pins, three source repos with C1→C2→C3 on main (backdated 30, 20, 10 days), read $(date -u +%Y-%m-%d). No version tag, pin C1: $notag_out. v1.0.0 on C1, pin C2: $behind_out. v1.0.0 on C2, pin C2 (main ahead): $tagged_out. ${DBOT_NOTE:+Job log: $DBOT_NOTE} Repos: https://github.com/$DBOT_CONSUMER"
  if [[ "$notag_out" != *"main's HEAD"* || "$behind_out" != *"main's HEAD"* || "$tagged_out" != *"main's HEAD"* ]]; then stalled=yes; fi
  if [[ "$stalled" == yes ]]; then
    conclude DBOT yes "The reference ops repo's daily main bump can't rely on Dependabot in every case; Renovate is ADR 0016's recorded alternative (slice 1.5, M7)." "Dependabot doesn't follow main in every case. $summary"
  else
    conclude DBOT no "" "Dependabot follows main in all three cases. $summary"
  fi
}
spike_dbot_read
pause

# ── 17 ────────────────────────────────────────────────────────────────────
stage "Deployment records and retention: read the result (ADR 0027)"
spike_ret_read() {
  need RET_RUN_ID "Stage 13 hasn't run the workflow yet; re-run the wizard to do it." || return 0
  begin R_RET || return 0
  local run dep at epoch age run_gone=no listed dep_state
  run=$(get RET_RUN_ID); dep=$(get RET_DEPLOYMENT_ID); at=$(get RET_AT); epoch=$(get RET_EPOCH)
  age=$(( ($(date +%s) - epoch) / 3600 ))
  say "Run $run wrote deployment record $dep at $at, $age hours ago, under 1-day retention."
  if gh api "repos/$RET_REPO/actions/runs/$run" --silent >/dev/null 2>&1; then
    listed=yes
  else
    listed=$(gh run list -R "$RET_REPO" -L 50 --json databaseId --jq "[.[] | select(.databaseId == $run)] | length" 2>/dev/null || echo "?")
    if [[ "$listed" == 0 ]]; then run_gone=yes; fi
  fi
  if [[ "$run_gone" != yes ]]; then
    ok "the run still exists, so GitHub hasn't swept it yet"
    if (( age < 24 )); then note "It is inside its 1 day. Re-run the wizard after $(day_offset +1)."
    else warn "It is past its 1 day; the sweep is periodic and undocumented. Try again in a few hours."; fi
    if (( age > 96 )) && confirm "Four days on, give up and record that the run was never deleted?"; then
      conclude RET no "" "Inconclusive: $age hours after a run under 1-day retention, GitHub still hadn't deleted the run, so whether the record outlives it wasn't observed. Record $dep still exists. https://github.com/$RET_REPO"
    fi
    return 0
  fi
  ok "the run is gone (deleted by retention)"
  if dep_state=$(gh api "repos/$RET_REPO/deployments/$dep" --jq '.environment' 2>/dev/null); then
    ok "deployment record $dep is still there (environment '$dep_state')"
    listed=$(gh api "repos/$RET_REPO/deployments?environment=previews" --jq 'length' 2>/dev/null || echo "?")
    conclude RET no "" "The deployment record outlives its run. Run $run (1-day retention, written $at) was deleted within $age hours; record $dep is still readable, and the 'previews' listing returns $listed record(s). https://github.com/$RET_REPO"
  else
    conclude RET yes "The teardown's find job lists the env/pr-* state keys (slice 2.2)." "The deployment record is deleted with its run. Run $run (1-day retention, written $at) and record $dep were both gone after $age hours. https://github.com/$RET_REPO"
  fi
}
spike_ret_read
pause

# ── 18 ────────────────────────────────────────────────────────────────────
stage "Write up the results"
SPIKES="KV RO LOCK REENC DO WF TAG SECRETS RET DBOT"
title_of() {
  case "$1" in
    KV)      printf 'Is a KV read served from the cacheTtl cache billed?' ;;
    RO)      printf 'Read-only planning: tofu plan -lock=false with a read-only R2 key' ;;
    LOCK)    printf 'R2 locking under contention' ;;
    REENC)   printf 'Which command re-encrypts an unchanged state' ;;
    DO)      printf 'How a Durable Object learns its own location' ;;
    WF)      printf 'Can Editor on links-data create and read a Workflow instance?' ;;
    TAG)     printf 'wrangler deploy --tag with exports, its read-back, and versions upload' ;;
    SECRETS) printf 'Does --secrets-file remove a hand-set secret?' ;;
    RET)     printf 'Does a deployment record outlive its run?' ;;
    DBOT)    printf 'How Dependabot bumps a main SHA pin' ;;
  esac
}
adrs_of() {
  case "$1" in
    KV) printf 'ADR 0006' ;; RO) printf 'ADR 0027' ;; LOCK) printf 'ADR 0027, ADR 0032' ;;
    REENC) printf 'ADR 0027' ;; DO) printf 'ADR 0017' ;; WF) printf 'ADR 0031 (and ADR 0024 if a permission is added)' ;;
    TAG) printf 'ADR 0031, ADR 0027' ;; SECRETS) printf 'ADR 0032, ADR 0016' ;; RET) printf 'ADR 0027' ;; DBOT) printf 'ADR 0016' ;;
  esac
}
PENDING=""; FALLBACKS=0
for s in $SPIKES; do
  if [[ -z "$(get "R_$s")" ]]; then PENDING+="$s "; fi
  if [[ "$(get "R_${s}_FALLBACK")" == yes ]]; then FALLBACKS=$((FALLBACKS + 1)); fi
done
{
  printf '## Spike results: slice 1.6, the undocumented facts\n\n'
  printf 'Written %s. Run on throwaway Workers, one KV namespace, one R2 bucket and five public repos, with OpenTofu %s and Wrangler %s. No deployment value is in this text.\n\n' \
    "$(date -u +%Y-%m-%d)" "$TOFU_VERSION" "$WRANGLER_VERSION"
  for s in $SPIKES; do
    printf '### %s\n\n' "$(title_of "$s")"
    if [[ -z "$(get "R_$s")" ]]; then printf '_Not run yet._\n\n'; continue; fi
    printf '%s\n\n' "$(get "R_$s")"
    if [[ "$(get "R_${s}_FALLBACK")" == yes ]]; then printf '**Fallback taken.** %s\n\n' "$(get "R_${s}_CHANGES")"
    else printf '**No fallback.** The design stands as written.\n\n'; fi
    printf 'Record in: %s.\n\n' "$(adrs_of "$s")"
  done
  printf '### Fallbacks, for #%s\n\n' "$PRD_NUMBER"
  if [[ "$FALLBACKS" == 0 ]]; then printf 'None taken so far.\n'
  else
    for s in $SPIKES; do
      if [[ "$(get "R_${s}_FALLBACK")" == yes ]]; then printf -- '- **%s** %s\n' "$(title_of "$s")" "$(get "R_${s}_CHANGES")"; fi
    done
  fi
} | scrub >"$RESULT_FILE"
for s in $SPIKES; do
  if [[ -z "$(get "R_$s")" ]]; then printf '  %s…%s %-8s not run yet\n' "$YELLOW" "$RESET" "$s"
  elif [[ "$(get "R_${s}_FALLBACK")" == yes ]]; then printf '  %s!%s %-8s fallback taken\n' "$YELLOW" "$RESET" "$s"
  else printf '  %s✓%s %-8s as designed\n' "$GREEN" "$RESET" "$s"; fi
done
printf '\n'
ok "wrote the write-up to $RESULT_FILE"
if [[ -n "$PENDING" ]]; then
  note "Still to run: $PENDING. Re-run the wizard for those; recorded spikes are skipped."
fi
if confirm "Post the write-up as a comment on $ISSUE_REPO#$ISSUE_NUMBER (as $GH_LOGIN)?"; then
  if COMMENT_URL=$(gh issue comment "$ISSUE_NUMBER" -R "$ISSUE_REPO" --body-file "$RESULT_FILE"); then ok "commented: $COMMENT_URL"
  else SKIPPED+=("comment on #$ISSUE_NUMBER: gh issue comment $ISSUE_NUMBER -R $ISSUE_REPO --body-file $RESULT_FILE"); warn "couldn't post the comment"; fi
else
  SKIPPED+=("comment on #$ISSUE_NUMBER: gh issue comment $ISSUE_NUMBER -R $ISSUE_REPO --body-file $RESULT_FILE")
fi
SKIPPED+=("record each result in its ADR (an agent can do this from $RESULT_FILE or the comment)")
if [[ "$FALLBACKS" -gt 0 ]]; then
  SKIPPED+=("summarise the $FALLBACKS fallback(s) in a comment on #$PRD_NUMBER, naming the slices (the write-up's last section)")
fi
pause

# ── 19 ────────────────────────────────────────────────────────────────────
stage "Remove every throwaway resource"
cleanup() {
  local c repo key dir="$WORK/links-data" headers
  if [[ -n "$PENDING" ]]; then
    warn "Not run yet: $PENDING"
    warn "Removing things now ends those spikes. The KV, retention and Dependabot ones need their"
    warn "resources until stages 15 to 17 have recorded a result."
    confirm "Remove everything anyway?" || { SKIPPED+=("re-run the wizard to finish: $PENDING, then remove the throwaway resources (this stage)"); return 0; }
  else
    confirm "Every spike is recorded. Remove the Workers, KV namespace, bucket and repos now?" \
      || { SKIPPED+=("remove the throwaway resources: re-run the wizard and answer yes at the last stage"); return 0; }
  fi
  if [[ -n "$CF_SETUP_TOKEN" ]]; then
    say "Workers (Wrangler asks you to confirm each delete):"
    if [[ -d "$dir" ]]; then
      wr "$CF_SETUP_TOKEN" "$dir" workflows delete "$WORKFLOW_NAME" || warn "couldn't delete the Workflow $WORKFLOW_NAME; check Workers → Workflows in the dashboard"
      wr "$CF_SETUP_TOKEN" "$dir" delete --name "$LD_WORKER" || SKIPPED+=("delete the Worker $LD_WORKER in the dashboard")
    fi
    wr "$CF_SETUP_TOKEN" "$WORK" delete --name "$KV_WORKER" || SKIPPED+=("delete the Worker $KV_WORKER in the dashboard")
    if [[ -n "$KV_NAMESPACE_ID" ]]; then
      wr "$CF_SETUP_TOKEN" "$WORK" kv namespace delete --namespace-id "$KV_NAMESPACE_ID" --skip-confirmation \
        || SKIPPED+=("delete the KV namespace $KV_WORKER in the dashboard")
    fi
    say "The bucket's objects, then the bucket:"
    for key in $(get STATE_KEYS); do
      wr "$CF_SETUP_TOKEN" "$WORK" r2 object delete "$BUCKET/$key" --remote >/dev/null 2>&1 || true
      wr "$CF_SETUP_TOKEN" "$WORK" r2 object delete "$BUCKET/$key.tflock" --remote >/dev/null 2>&1 || true
    done
    if wr "$CF_SETUP_TOKEN" "$WORK" r2 bucket delete "$BUCKET"; then ok "deleted the bucket $BUCKET"
    else
      warn "the bucket isn't empty or couldn't be deleted"
      SKIPPED+=("empty and delete the R2 bucket $BUCKET (dashboard: the bucket → Settings → Empty Bucket, then Delete)")
    fi
  fi
  say "The tokens. Only you can delete these:"
  open_url "https://dash.cloudflare.com/$CF_ACCOUNT_ID/home"
  step "Manage Account → Account API Tokens: delete $PREFIX-setup, $PREFIX-admin and $PREFIX-plan."
  step "R2 → Account Details → API Tokens → Manage: delete $PREFIX-rw and $PREFIX-ro."
  step "While there, check Workers & Pages, Workers KV, R2 and Workflows for anything named $PREFIX-…"
  if ! confirm "Are all five tokens deleted and nothing named $PREFIX-… left?"; then
    SKIPPED+=("delete the Cloudflare tokens $PREFIX-setup, $PREFIX-admin, $PREFIX-plan, $PREFIX-rw, $PREFIX-ro")
  fi
  say "The GitHub repos:"
  headers=$(gh api -i user 2>/dev/null | grep -i '^x-oauth-scopes:' || true)
  if ! grep -qw delete_repo <<<"$headers"; then
    note "gh needs the 'delete_repo' scope to delete a repo."
    if confirm "Run: gh auth refresh -h github.com -s delete_repo ?"; then
      gh auth refresh -h github.com -s delete_repo || warn "gh auth refresh failed"
    fi
  fi
  for repo in "$RET_REPO" "$DBOT_CONSUMER" $(for c in $DBOT_CASES; do printf '%s ' "$GH_LOGIN/$PREFIX-dbot-src-$c"; done); do
    gh repo view "$repo" >/dev/null 2>&1 || continue
    if gh repo delete "$repo" --yes >/dev/null 2>&1; then ok "deleted $repo"
    else SKIPPED+=("delete https://github.com/$repo/settings"); warn "couldn't delete $repo"; fi
  done
  if confirm "Delete the saved tokens and work files in $STATE_DIR (the write-up is kept)?"; then
    rm -rf "$WORK" "$LOGS" "$ENV_FILE"
    ok "removed; $RESULT_FILE is all that is left"
  else
    SKIPPED+=("delete $ENV_FILE (it holds the throwaway tokens)")
  fi
}
cleanup
pause

finish
